<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="MyTestCase-20200609232704" tests="2" time="0.018">
	<testcase classname="MyTestCase" name="test_hello" time="0.015">
		<error message="b'&lt;html&gt;\n    &lt;head&gt;\n      &lt;!--Let browser[1192 chars]tml&gt;' != b'I am here to help!\n'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 15, in test_hello
    self.assertEqual(rv.data, b'I am here to help!\n')
AssertionError: b'<html>\n    <head>\n      <!--Let browser[1192 chars]tml>' != b'I am here to help!\n'
]]>		</error>
	</testcase>
	<testcase classname="MyTestCase" name="test_hello_index" time="0.003">
		<error message="'404 NOT FOUND' != '200 OK'
- 404 NOT FOUND
+ 200 OK
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 19, in test_hello_index
    self.assertEqual(rv.status, '200 OK')
AssertionError: '404 NOT FOUND' != '200 OK'
- 404 NOT FOUND
+ 200 OK

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
